---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: example-com
  namespace: default
spec:
  secretName: example-com-tls
  issuerRef:
    name: ca-issuer-default
    kind: Issuer
  commonName: example.com
  dnsNames:
    - www.example.com